version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: patient_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: patients
      DB_USERNAME: postgres
      DB_PASSWORD: secret

  db:
    image: postgres:14
    container_name: patient_db
    environment:
      POSTGRES_DB: patients
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: patient_mailhog
    ports:
      - "8025:8025"

volumes:
  db_data:
